<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-03-29T10:26:06Z" name="Default suite" finished-at="2022-03-29T10:26:37Z" duration-ms="31131">
    <groups>
    </groups>
    <test started-at="2022-03-29T10:26:06Z" name="Default test" finished-at="2022-03-29T10:26:37Z" duration-ms="31131">
      <class name="org.testng.TestHome3">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:org.testng.TestHome3@3148f668]" started-at="2022-03-29T10:26:06Z" name="beforeMethod" finished-at="2022-03-29T10:26:09Z" duration-ms="2971" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="test()[pri:0, instance:org.testng.TestHome3@3148f668]" started-at="2022-03-29T10:26:09Z" name="test" finished-at="2022-03-29T10:26:37Z" duration-ms="28097" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Test1 expected [true] but found [false],
Test2 expected [watches] but found [MEGIR 2064 Business Quartz Watch Men Stainless Steel Chronograph Wrist Watch - Silver]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Test1 expected [true] but found [false],
Test2 expected [watches] but found [MEGIR 2064 Business Quartz Watch Men Stainless Steel Chronograph Wrist Watch - Silver]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at org.testng.TestHome3.test(TestHome3.java:65)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- org.testng.TestHome3 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
